import fs from "node:fs";
import path from "node:path";
import { WORKTREES_DIR } from "../config/paths.js";
import type { DiscoveredEnvVar, SessionMeta } from "../session/store.js";
import { log, UserError } from "../util/log.js";

export interface PatchChange {
  name: string;
  role: DiscoveredEnvVar["role"];
  from?: string;
  to: string;
}

/** Compute the rewritten value for a var given the proxy URL, or null to leave it alone. */
export function rewriteValue(
  role: DiscoveredEnvVar["role"],
  proxyPort: number
): string | null {
  const httpsUrl = `https://localhost:${proxyPort}`;
  switch (role) {
    case "auth0-domain":
      return `localhost:${proxyPort}`; // bare host; SDK prepends https://
    case "auth0-issuer":
      return `${httpsUrl}/`;
    case "api-base":
      return httpsUrl;
    // Audience + client id are accepted as-is by our proxy — leave them untouched.
    case "auth0-audience":
    case "auth0-client-id":
      return null;
  }
}

/** Parse an existing dotenv file into ordered key/value pairs. */
function readEnvFile(file: string): Map<string, string> {
  const map = new Map<string, string>();
  if (!fs.existsSync(file)) return map;
  for (const raw of fs.readFileSync(file, "utf8").split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    map.set(
      line
        .slice(0, eq)
        .replace(/^export\s+/, "")
        .trim(),
      line.slice(eq + 1)
    );
  }
  return map;
}

/**
 * Write `.env.local` in the worktree so Auth0 + API base vars point at the proxy.
 * `.env.local` is the highest-precedence, git-ignored env file in both Next.js and Vite.
 * Only ever writes inside the managed worktree tree — never a user's real checkout.
 */
export function patchEnv(session: SessionMeta): {
  file: string;
  changes: PatchChange[];
} {
  const worktree = session.worktree;
  const resolved = path.resolve(worktree);
  if (!resolved.startsWith(path.resolve(WORKTREES_DIR) + path.sep)) {
    throw new UserError(
      `refusing to patch env outside managed worktrees: ${resolved}`
    );
  }
  if (session.proxyPort == null) {
    throw new UserError("session has no proxyPort; start the proxy first");
  }

  const file = path.join(worktree, ".env.local");
  const existing = readEnvFile(file);
  const changes: PatchChange[] = [];

  for (const v of session.envVars) {
    const to = rewriteValue(v.role, session.proxyPort);
    if (to == null) continue;
    changes.push({
      name: v.name,
      role: v.role,
      from: existing.get(v.name) ?? v.originalValue,
      to,
    });
    existing.set(v.name, to);
  }

  const header = [
    "# Generated by sauce-control — points Auth0 + API traffic at the local mock proxy.",
    "# Safe to delete; regenerated on next `launch`.",
    "",
  ];
  const lines = [...existing.entries()].map(([k, val]) => `${k}=${val}`);
  fs.writeFileSync(file, header.concat(lines).join("\n") + "\n");

  for (const c of changes) log.dim(`  ${c.name}=${c.to}`);
  log.success(
    `Patched ${path.relative(worktree, file)} (${changes.length} vars)`
  );
  return { file, changes };
}
